apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: manufacturing-recommendation-api
  namespace: manufacturing-analytics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: manufacturing-recommendation-api

