apiVersion: v1
kind: Service
metadata:
  name: manufacturing-recommendation-api
  namespace: manufacturing-analytics
spec:
  selector:
    app: manufacturing-recommendation-api
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP

